### ISSUE TITLE
lfads-output did not include train_inds and valid_inds.

### ISSUE THREAD

**Issue by Riverside-ms** [arsedler9/lfads-torch#11]
Hi Andrew,

I was able to proceed through the tutorial and got the lfads-output.
However, the lfads-output files did not contain train_inds and valid_inds as variables,
and I got an error in "Load LFADS factors and rates from output files".

I remembered that I had defined valid_inds as a multiple of 5 in "Saving the data for lfads-torch". 
So instead of reading train_inds and valid_inds from lfads-output, 
I defined them as not multiples of 5 and multiples of 5, thus avoiding the error.
Is this the correct way to do this?

The lfads-output downloaded at the beginning of 3_evaluation.ipynb contained train_inds and valid_inds, but not followed the multiple of 5 rule.

Thanks.

**Comment by arsedler9** [comment]
Thanks for pointing this out! You're right, the data indices were not saved by the `1_data_prep.ipynb` notebook. I fixed this in the above PR. Your approach of manually recalculating the indices should also work. As you mentioned, the provided LFADS output files used a different train / valid split.
