### ISSUE TITLE
data help

### ISSUE THREAD

**Issue by wwrlearner** [arsedler9/lfads-torch#26]
Hi, 
Andrew,
Could you please provide me for the synth_data? I'm interested in the results of three synth_data in the paper supplymentary.

**Comment by arsedler9** [comment]
Hey @wwrlearner, the `lfads-torch` paper didn't have a supplement or synthetic data, but maybe you're referring to [this repo](https://github.com/snel-repo/expressive-latent-dynamics-paper)? You can find some synthetic datasets there.

**Comment by arsedler9** [comment]
Hi @wwrlearner, this part of the script is trying to plot `RasterPlot.n_samples` examples of spikes, inferred rates, and inferred inputs. In this case, `RasterPlot.n_samples=3` (the default) and it looks like indexing is going out of bounds. Is your batch size smaller than 3? You can always turn off the `RasterPlot` callback by removing it from the list of callbacks in your config.

**Comment by wwrlearner** [comment]
Thank you,
      I find some hyper-parameters in the table and  dataset settings, but I can't reproduce the results of  Lorenz data in the supplementary figure 2. Could you please provide me with more information about how to get the supplementary figure 2?
      For example, are there some details of training Lorenz system data that are not represented in the appendices？ After processing the Lorenz system data using the LFADS model, how do you utilize the figures drawn from the factors data?

**Comment by arsedler9** [comment]
Can you post a screenshot of the plot you're referring to?

**Comment by wwrlearner** [comment]
Sure! The figure is as follows.
![image](https://github.com/user-attachments/assets/0acc423c-0eb8-48f2-9483-9aead00754eb)

**Comment by arsedler9** [comment]
Ahh, this is from the original LFADS paper, which I wasn't involved in. My understanding is that they (1) simulated a Lorenz attractor in 3D, (2) used a linear + exponential mapping to project the attractor into firing rates in 30D neural space, (3) sampled spike counts from the firing rates, (4) modeled the data with LFADS, and (5) used linear regression to project LFADS factors back onto the original Lorenz attractor that generated the data. Unfortunately I can't help much more with that-- I'd refer you to that paper or that paper's authors for more information. Good luck!
