### ISSUE TITLE
A comment on Installation Instruction

### ISSUE THREAD

**Issue by timkimd** [arsedler9/lfads-torch#6]
Hi Andrew,

Thank you for making this code pack available!

I just wanted to note that in installing lfads-torch on my system, I needed to do the following instead of what was written in the current description for installation.

git clone git@github.com:arsedler9/lfads-torch.git (didn't work)
 
**git clone https://github.com/arsedler9/lfads-torch** (works)

conda create --name lfads-torch python=3.9
conda activate lfads-torch

**pip install scikit-learn**

cd lfads-torch
pip install -e .
pre-commit install

Thanks!

**Comment by arsedler9** [comment]
Thanks @timkimd! Good points. For the first command to work, you'll just need to add your SSH key to GitHub. I agree that recommending HTTP cloning would probably be simpler for people who haven't set that up, so I went ahead and made that change on `main`. We also added `scikit-learn` to `requirements.txt`, which should fix the second issue.
